# Generated by Django 3.1.6 on 2021-02-24 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('desc', models.TextField()),
                ('created_at', models.DateTimeField()),
                ('due_date', models.DateTimeField()),
            ],
        ),
    ]
