# Generated by Django 3.1.6 on 2021-02-26 16:44

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('trello_app', '0003_auto_20210224_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 26, 16, 44, 41, 42520, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='tasklist',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 26, 16, 44, 40, 998982, tzinfo=utc)),
        ),
    ]
